# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-18 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, verbose_name='\u56fe\u4e66\u540d')),
                ('book_no', models.CharField(max_length=50, verbose_name='\u56fe\u4e66\u7f16\u53f7')),
                ('book_info', models.TextField(verbose_name='\u56fe\u4e66\u8be6\u60c5')),
                ('book_url', models.URLField(max_length=500, verbose_name='\u56fe\u4e66\u94fe\u63a5')),
                ('stars', models.FloatField(max_length=10, verbose_name='\u8bc4\u5206')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u4eba\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('image', models.ImageField(upload_to='book/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u56fe\u4e66',
                'verbose_name_plural': '\u56fe\u4e66',
            },
        ),
        migrations.CreateModel(
            name='BookDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(max_length=50, verbose_name='\u56fe\u4e66\u7f16\u53f7')),
                ('book_name', models.CharField(max_length=50, verbose_name='\u4e66\u540d')),
                ('book_author', models.CharField(max_length=50, verbose_name='\u4f5c\u8005')),
                ('book_public', models.CharField(max_length=50, verbose_name='\u51fa\u7248\u793e')),
                ('book_year', models.CharField(max_length=25, verbose_name='\u51fa\u7248\u65f6\u95f4')),
                ('book_page', models.IntegerField(default=0, verbose_name='\u9875\u6570')),
                ('book_price', models.CharField(max_length=30, verbose_name='\u4ef7\u683c')),
                ('votenum', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u4eba\u6570')),
                ('stars', models.FloatField(max_length=10, verbose_name='\u8bc4\u5206')),
                ('book_intro', models.TextField(verbose_name='\u56fe\u4e66\u7b80\u4ecb')),
                ('author_intro', models.TextField(verbose_name='\u4f5c\u8005\u7b80\u4ecb')),
                ('book_others', models.TextField(verbose_name='\u4e1b\u4e66\u4fe1\u606f')),
                ('mu_lu', models.TextField(verbose_name='\u76ee\u5f55')),
                ('recommendations', models.TextField(verbose_name='\u76f8\u5173\u63a8\u8350')),
                ('comments', models.TextField(verbose_name='\u8bc4\u8bba')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u4eba\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u56fe\u4e66\u8be6\u60c5',
                'verbose_name_plural': '\u56fe\u4e66\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='BookKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20, verbose_name='\u56fe\u4e66\u5c0f\u7c7b')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u56fe\u4e66\u5177\u4f53\u7c7b\u522b',
                'verbose_name_plural': '\u56fe\u4e66\u5177\u4f53\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=20, verbose_name='\u56fe\u4e66\u5927\u7c7b')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u56fe\u4e66\u603b\u7c7b\u522b',
                'verbose_name_plural': '\u56fe\u4e66\u603b\u7c7b\u522b',
            },
        ),
        migrations.AddField(
            model_name='bookkind',
            name='book_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.BookTag', verbose_name='\u5927\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.BookKind', verbose_name='\u5c0f\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.BookTag', verbose_name='\u5927\u7c7b\u522b'),
        ),
    ]
