# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20170418_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetail',
            name='image',
            field=models.ImageField(default='', upload_to='book_detail/%Y/%m', verbose_name='\u5927\u56fe'),
        ),
    ]
