# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookdetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u8f6e\u64ad'),
        ),
    ]
