# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_bookdetail_book_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetail',
            name='book_author',
            field=models.CharField(max_length=100, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='book_name',
            field=models.CharField(max_length=100, verbose_name='\u4e66\u540d'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='book_public',
            field=models.CharField(max_length=100, verbose_name='\u51fa\u7248\u793e'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='book_year',
            field=models.CharField(max_length=20, verbose_name='\u51fa\u7248\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='bookdetail',
            name='recommendations',
            field=models.CharField(max_length=250, verbose_name='\u76f8\u5173\u63a8\u8350'),
        ),
    ]
