# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.CharField(choices=[('sj', '\u4e66\u7c4d'), ('dy', '\u7535\u5f71')], default='sj', max_length=5, verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
    ]
