# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20170423_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='book',
        ),
    ]
