# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20170512_1326'),
        ('operation', '0004_remove_userbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='\u56fe\u4e66'),
            preserve_default=False,
        ),
    ]
