# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_userbook_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermovie',
            name='movie',
        ),
    ]
