# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20170513_1026'),
        ('operation', '0006_remove_usermovie_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermovie',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='\u7535\u5f71'),
            preserve_default=False,
        ),
    ]
