# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_usermovie_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomments',
            name='book',
        ),
        migrations.RemoveField(
            model_name='moviecomments',
            name='movie',
        ),
    ]
