# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20170512_1326'),
        ('movies', '0004_auto_20170513_1026'),
        ('operation', '0008_auto_20170513_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcomments',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.Book', verbose_name='\u56fe\u4e66'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviecomments',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie', verbose_name='\u7535\u5f71'),
            preserve_default=False,
        ),
    ]
