# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20170522_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecomments',
            name='dislikenum',
            field=models.IntegerField(default=0, verbose_name='\u88ab\u8e29\u6b21\u6570'),
        ),
        migrations.AddField(
            model_name='moviecomments',
            name='likenum',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u8d5e\u6b21\u6570'),
        ),
    ]
