# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 23:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u540d')),
                ('movie_no', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u7f16\u53f7')),
                ('movie_info', models.TextField(verbose_name='\u7535\u5f71\u8be6\u60c5')),
                ('movie_url', models.CharField(max_length=500, verbose_name='\u7535\u5f71\u94fe\u63a5')),
                ('stars', models.FloatField(max_length=10, verbose_name='\u8bc4\u5206')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u6d4f\u89c8\u4eba\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('image', models.ImageField(upload_to='movie/%Y/%m', verbose_name='\u5c01\u9762\u56fe')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7535\u5f71',
                'verbose_name_plural': '\u7535\u5f71',
            },
        ),
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_no', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u7f16\u53f7')),
                ('movie_name', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u540d')),
                ('movie_year', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u5e74\u4efd')),
                ('movie_director', models.CharField(max_length=25, verbose_name='\u7535\u5f71\u5bfc\u6f14')),
                ('movie_pl', models.CharField(max_length=500, verbose_name='\u7535\u5f71\u7f16\u5267')),
                ('movie_actor', models.CharField(max_length=800, verbose_name='\u7535\u5f71\u4e3b\u6f14')),
                ('movie_type', models.CharField(default='\u65e0\u660e\u786e\u7c7b\u578b', max_length=100, verbose_name='\u7535\u5f71\u7c7b\u578b')),
                ('country', models.CharField(max_length=100, verbose_name='\u5236\u7247\u56fd\u5bb6/\u5730\u533a')),
                ('language', models.CharField(max_length=20, verbose_name='\u8bed\u8a00')),
                ('movie_ReleaseDate', models.CharField(max_length=20, verbose_name='\u4e0a\u6620\u65e5\u671f')),
                ('runtime', models.IntegerField(default=0, verbose_name='\u7535\u5f71\u65f6\u957f')),
                ('votenum', models.IntegerField(default=0, verbose_name='\u8bc4\u8bba\u4eba\u6570')),
                ('stars', models.FloatField(max_length=10, verbose_name='\u8bc4\u5206')),
                ('movie_intro', models.TextField(verbose_name='\u7535\u5f71\u7b80\u4ecb')),
                ('recommendations', models.TextField(verbose_name='\u76f8\u5173\u63a8\u8350')),
                ('comments', models.TextField(verbose_name='\u8bc4\u8bba')),
                ('click_nums', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u4eba\u6570')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='\u6536\u85cf\u4eba\u6570')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7535\u5f71\u8be6\u60c5',
                'verbose_name_plural': '\u7535\u5f71\u8be6\u60c5',
            },
        ),
        migrations.CreateModel(
            name='MovieKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u540d')),
                ('movie_no', models.CharField(max_length=50, verbose_name='\u7535\u5f71\u7f16\u53f7')),
                ('movie_kind', models.IntegerField(default=1998, verbose_name='\u4e0a\u6620\u5e74\u4efd')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7535\u5f71\u7c7b\u522b',
                'verbose_name_plural': '\u7535\u5f71\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u7c7b\u522b\u540d\u79f0')),
                ('desc', models.CharField(max_length=200, verbose_name='\u7c7b\u522b\u63cf\u8ff0')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.AddField(
            model_name='moviedetail',
            name='movie_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MovieTag', verbose_name='\u7535\u5f71\u7c7b\u522b'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MovieKind', verbose_name='\u5e74\u4efd'),
        ),
    ]
