# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-23 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_year',
            field=models.ForeignKey(default='1988', on_delete=django.db.models.deletion.CASCADE, to='movies.MovieTag', verbose_name='\u5e74\u4efd'),
        ),
        migrations.AlterField(
            model_name='moviekind',
            name='movie_kind',
            field=models.IntegerField(default=1988, verbose_name='\u4e0a\u6620\u5e74\u4efd'),
        ),
    ]
