# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_is_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetail',
            name='movie_tag',
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='movie_detail/%Y/%m', verbose_name='\u5c01\u9762\u56fe'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=100, verbose_name='\u7535\u5f71\u540d'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_no',
            field=models.CharField(max_length=100, verbose_name='\u7535\u5f71\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.CharField(max_length=150, verbose_name='\u7535\u5f71\u94fe\u63a5'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.CharField(max_length=10, verbose_name='\u8bc4\u5206'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='movie_director',
            field=models.CharField(max_length=100, verbose_name='\u7535\u5f71\u5bfc\u6f14'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='movie_name',
            field=models.CharField(max_length=100, verbose_name='\u7535\u5f71\u540d'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='movie_no',
            field=models.CharField(max_length=20, verbose_name='\u7535\u5f71\u7f16\u53f7'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='movie_pl',
            field=models.CharField(max_length=300, verbose_name='\u7535\u5f71\u7f16\u5267'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='movie_year',
            field=models.CharField(max_length=10, verbose_name='\u7535\u5f71\u5e74\u4efd'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='runtime',
            field=models.CharField(max_length=10, verbose_name='\u7535\u5f71\u65f6\u957f'),
        ),
        migrations.AlterField(
            model_name='moviedetail',
            name='stars',
            field=models.CharField(max_length=15, verbose_name='\u8bc4\u5206'),
        ),
    ]
