# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20170513_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='stars',
            field=models.FloatField(max_length=10, verbose_name='\u8bc4\u5206'),
        ),
    ]
